spring:
  redis:
    host: localhost
    port: 6379
    lettuce:  #lettuce是springboot 默认连接池
      pool:
        max-active: 8 #最大连接
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最大空闲数
        max-wait: 100 #连接等待时间